import { Activity, Scale, Coffee, Moon, TrendingUp, Calculator, Hammer, Sparkles, GraduationCap } from "lucide-react";

export const categories = [
    {
        title: "General Health / Lifestyle",
        icon: <Activity className="h-6 w-6 text-primary" />,
        calculators: [
            { name: "Bra Size Calculator", href: "/bra-size-calculator-uk", desc: "US Standard Sizing" },
            { name: "Child Growth Chart", href: "/child-growth-chart-calculator-uk", desc: "Estimate height/weight percentiles" },
            { name: "BMI Calculator", href: "/bmi-calculator-uk", desc: "Body Mass Index" },
            { name: "Reverse BMI", href: "/reverse-bmi-calculator", desc: "Find weight for a target BMI" },
            { name: "Child BMI", href: "/child-bmi-calculator", desc: "BMI percentile for children" },
            { name: "Pregnancy Weight Gain Calculator UK", href: "/pregnancy-weight-gain-calculator", desc: "Healthy weight gain during pregnancy" },
            { name: "BMR Calculator", href: "/bmr-calculator-to-lose-weight", desc: "Basal Metabolic Rate" },
            { name: "Heart Age", href: "/heart-age-calculator-uk", desc: "Estimate your cardiovascular age" },
            { name: "Waist-to-Height", href: "/waist-to-height-ratio-calculator", desc: "Better indicator than BMI" },
            { name: "Life Expectancy", href: "/life-expectancy-calculator-uk", desc: "Estimate based on habits" },
            { name: "Frailty Score", href: "/frailty-score-calculator-uk", desc: "Assess physical decline" },
            { name: "Ape Index", href: "/ape-index-calculator", desc: "Arm span vs height ratio" },
            { name: "Visceral Fat", href: "/visceral-fat-calculator", desc: "Estimate hidden belly fat" },
            { name: "Pregnancy BMI UK", href: "/pregnancy-bmi-calculator-uk", desc: "Healthy weight gain during pregnancy" },
            { name: "Childcare Cost", href: "/childcare-cost-calculator-uk", desc: "Estimate UK childcare expenses" },
            { name: "Pregnancy Due Date", href: "/pregnancy-due-date-calculator-uk", desc: "Calculate your estimated delivery date" },
            { name: "School Age", href: "/school-age-calculator-uk", desc: "Find which school year a child belongs in" },
            { name: "Hair Transplant Graft", href: "/hair-transplant-graft-calculator-uk", desc: "Estimate complete UK/Turkey costs" },
        ],
    },
    {
        title: "Fitness & Diet",
        icon: <Scale className="h-6 w-6 text-primary" />,
        calculators: [
            { name: "Calorie Deficit", href: "/calorie-deficit-calculator-uk", desc: "Calculate weight loss calories" },
            { name: "VO2 Max", href: "/vo2-max-calculator", desc: "Maximal oxygen uptake" },
            { name: "Water Intake", href: "/water-intake-calculator", desc: "Daily hydration needs" },
            { name: "Intermittent Fasting", href: "/intermittent-fasting-calculator", desc: "Eating window planner" },
            { name: "Water Fast", href: "/water-fast-calculator", desc: "Estimate weight loss during fast" },
            { name: "Breastfeeding Calories", href: "/breastfeeding-calorie-calculator-uk", desc: "Daily caloric needs for nursing" },
            { name: "Weight Gain", href: "/calorie-calculator-to-gain-weight-uk", desc: "Calories needed to build lean mass" },
            { name: "Dog Calories", href: "/dog-calorie-calculator-uk", desc: "Daily energy needs for your dog" },
            { name: "Resting Calories", href: "/resting-calorie-calculator-uk", desc: "Calories burned at rest" },
            { name: "BMI Calculator UK", href: "/bmi-calculator-uk", desc: "Body mass index and healthy weight" },
            { name: "Dental Implant Cost", href: "/dental-implant-cost-calculator-uk", desc: "UK dental treatment price guide" },
            { name: "Rucking Calories", href: "/rucking-calorie-calculator-uk", desc: "Burn rate with a weighted pack" },
            { name: "TDEE Calculator", href: "/tdee-calculator-uk", desc: "Daily energy expenditure and calories" },
            { name: "Swimming Calories", href: "/swimming-calorie-calculator-uk", desc: "Workout intensity based calorie burn" },
        ],
    },
    {
        title: "Finance",
        icon: <Activity className="h-6 w-6 text-primary" />,
        calculators: [
            { name: "Salary Calculator", href: "/salary-calculator-uk", desc: "Calculate take-home pay after tax and NI" },
            { name: "Income Tax Calculator", href: "/income-tax-calculator-uk", desc: "UK Income Tax and National Insurance" },
            { name: "VAT Calculator", href: "/vat-calculator-uk", desc: "Add or remove UK VAT" },
            { name: "Redundancy Calculator", href: "/redundancy-calculator-uk", desc: "Calculate Statutory Redundancy Pay (SRP)" },
            { name: "Holiday Budget", href: "/holiday-calculator-uk", desc: "Estimate your vacation cost" },
            { name: "Annual Leave", href: "/annual-leave-calculator-uk", desc: "UK statutory holiday entitlement" },
            { name: "Loan Calculator", href: "/loan-calculator-uk", desc: "Monthly payments and total interest" },
            { name: "Notice Period", href: "/notice-period-calculator-uk", desc: "Statutory and contractual notice helper" },
            { name: "Junior Doctor Salary", href: "/junior-doctor-salary-calculator-uk", desc: "Net pay for junior medical staff" },
            { name: "Equity Release", href: "/equity-release-calculator-uk", desc: "Unlock tax-free cash from your property" },
            { name: "Pension Drawdown", href: "/pension-drawdown-calculator-uk", desc: "Retirement pot projection" },
            { name: "Electricity Cost", href: "/electricity-cost-calculator-uk", desc: "Calculate appliance running costs" },
            { name: "Gas Bill", href: "/gas-bill-calculator-uk", desc: "Estimate monthly gas expenditure" },
            { name: "Corporation Tax", href: "/corporation-tax-calculator-uk", desc: "Calculate your limited company tax bill" },
            { name: "Capital Gains Tax", href: "/capital-gains-tax-calculator-uk", desc: "Calculate UK CGT on property & shares" },
        ],
    },
    {
        title: "Automotive",
        icon: <Activity className="h-6 w-6 text-primary" />,
        calculators: [
            { name: "Mileage Claim", href: "/mileage-calculator-uk", desc: "Calculate business travel expense" },
            { name: "Road Tax", href: "/road-tax-calculator-uk", desc: "UK Vehicle Excise Duty" },
            { name: "Fuel Cost", href: "/fuel-cost-calculator-uk", desc: "Journey petrol/diesel cost" },
            { name: "Speeding Fine", href: "/speeding-fine-calculator-uk", desc: "UK Penalty Guidelines" },
            { name: "Car Insurance", href: "/car-insurance-calculator-uk", desc: "Rough premium estimator" },
            { name: "Car Write-Off", href: "/car-insurance-write-off-calculator-uk", desc: "Estimate damage vs value" },
            { name: "Drink Drive Limit", href: "/drink-drive-limit-calculator-uk", desc: "Estimate BAC levels" },
            { name: "Taxi Fare", href: "/taxi-fare-calculator-uk", desc: "UK cab fare estimator" },
            { name: "EV Charging Cost", href: "/ev-charging-cost-calculator-uk", desc: "Calculate home/public charging" },
            { name: "Car Accident Comp", href: "/car-accident-compensation-calculator-uk", desc: "Estimate injury settlement" },
            { name: "Car Depreciation", href: "/car-depreciation-calculator-uk", desc: "Calculate vehicle value loss" },
            { name: "Car Tax Refund", href: "/car-tax-refund-calculator-uk", desc: "Estimated VED refund amount" },
            { name: "Car Towing Cost", href: "/car-towing-cost-calculator-uk", desc: "Estimate vehicle recovery fees" },
            { name: "Electric vs Petrol", href: "/petrol-vs-electric-car-running-cost-calculator-uk", desc: "Total cost of ownership comparison" },
            { name: "Used Car Tax", href: "/used-car-tax-calculator-uk", desc: "Calculate VED for older vehicles" },
            { name: "Journey Cost", href: "/journey-cost-calculator-uk", desc: "Total fuel and toll costs for a trip" },
            { name: "PCP Car Finance", href: "/pcp-car-finance-calculator-uk", desc: "Estimate monthly payments & balloon" },
        ],
    },
    {
        title: "Home & Property",
        icon: <Activity className="h-6 w-6 text-primary" />,
        calculators: [
            { name: "BTU Radiator", href: "/btu-calculator-uk", desc: "Calculate room heating needs" },
            { name: "Roof Replacement", href: "/roof-replacement-cost-calculator-uk", desc: "Estimate new pitched roof cost" },
            { name: "Flat Roof Cost", href: "/flat-roof-replacement-cost-calculator-uk", desc: "Estimate flat roof replacement" },
            { name: "Removal Costs", href: "/removal-costs-calculator-uk", desc: "Estimate house moving fees" },
            { name: "Heat Pump Cost", href: "/heat-pump-cost-calculator-uk", desc: "UK heat pump estimator" },
            { name: "Double Glazing", href: "/double-glazing-cost-calculator-uk", desc: "Estimate new windows cost" },
            { name: "Tree Removal", href: "/tree-removal-cost-calculator-uk", desc: "Estimate tree felling costs" },
            { name: "Soffit & Fascia", href: "/soffit-and-fascia-cost-calculator", desc: "Estimate roofline replacement" },
            { name: "Mortgage Calculator UK", href: "/mortgage-calculator-uk", desc: "Calculate monthly EMI and total interest" },
            { name: "Architects Fee", href: "/architects-fee-calculator-uk", desc: "Estimate professional design costs" },
            { name: "Cavity Insulation", href: "/cavity-wall-insulation-cost-calculator-uk", desc: "Save on energy bills with insulation" },
            { name: "Garage Roof", href: "/garage-roof-replacement-cost-calculator-uk", desc: "Replace felt or metal garage roofs" },
            { name: "House Extension", href: "/house-extension-cost-calculator-uk", desc: "General guide for extension budgeting" },
            { name: "House Survey", href: "/house-survey-cost-calculator-uk", desc: "Homeybuyer or structural survey fees" },
            { name: "Loft Conversion", href: "/loft-conversion-cost-calculator-uk", desc: "Value added vs construction cost" },
            { name: "Bathroom Reno", href: "/small-bathroom-renovation-cost-calculator-uk", desc: "Budgeting for a compact bathroom refresh" },
            { name: "Solar Panel Cost", href: "/solar-panel-cost-calculator-uk", desc: "Installation fees and energy savings" },
            { name: "Dormer Cost", href: "/dormer-cost-calculator-uk", desc: "Estimate UK dormer loft conversion costs" },
        ],
    },
    {
        title: "Construction & DIY",
        icon: <Hammer className="h-6 w-6 text-primary" />,
        calculators: [
            { name: "Concrete Calculator", href: "/concrete-calculator-uk", desc: "Calculate concrete volume and bags needed" },
            { name: "Garden Wall Cost", href: "/building-garden-wall-cost-calculator-uk", desc: "Estimate bricks and labor for a wall" },
            { name: "Decking Cost", href: "/decking-cost-calculator-uk", desc: "Materials and labor for garden decking" },
            { name: "Epoxy Flooring", href: "/epoxy-flooring-cost-calculator-uk", desc: "Cost for resin garage or workshop floors" },
            { name: "Self-Levelling", href: "/self-levelling-compound-calculator-uk", desc: "Bags needed for floor preparation" },
            { name: "Tarmac Driveway", href: "/tarmac-driveway-cost-calculator-uk", desc: "Estimate new drive or resurfacing" },
        ],
    },
    {
        title: "Misc & Lifestyle",
        icon: <Coffee className="h-6 w-6 text-primary" />,
        calculators: [
            { name: "Tattoo Cost", href: "/tattoo-cost-calculator-uk", desc: "Estimate UK tattoo pricing" },
            { name: "University Grade", href: "/university-grade-calculator-uk", desc: "Calculate degree classification" },
            { name: "Dog Bite Comp", href: "/dog-bite-compensation-calculator-uk", desc: "Estimate animal attack settlement" },
            { name: "Pet Transport", href: "/pet-transport-cost-calculator-uk", desc: "Estimate animal relocation fees" },
        ],
    },
    {
        title: "Maths & Percentages",
        icon: <Calculator className="h-6 w-6 text-primary" />,
        calculators: [
            { name: "Percentage Calculator", href: "/percentage-calculator-uk", desc: "Calculate fractions, differences, and percentage increases" },
            { name: "Average Percentage", href: "/average-percentage-calculator-uk", desc: "Find the mean of several percentages" },
            { name: "Percentage Decrease", href: "/percentage-decrease-calculator-uk", desc: "Calculate reduction from original value" },
            { name: "Percentage Off", href: "/percentage-off-calculator-uk", desc: "Discount helper for shopping" },
            { name: "Reverse Percentage", href: "/reverse-percentage-calculator-uk", desc: "Original price before tax or discount" },
        ],
    },
    {
        title: "Sleep",
        icon: <Moon className="h-6 w-6 text-primary" />,
        calculators: [
            { name: "Epworth Sleepiness", href: "/epworth-sleepiness-scale-calculator", desc: "Daytime sleepiness scale" },
            { name: "Sleep Debt", href: "/sleep-debt-calculator", desc: "Calculate accumulated lost sleep" },
        ],
    },
    {
        title: "UK Stock Market & Investments",
        icon: <TrendingUp className="h-6 w-6 text-primary" />,
        calculators: [
            { name: "UK Capital Gains Tax (CGT)", href: "/uk-stock-capital-gains-tax-calculator", desc: "Calculate tax on share/investment sales" },
            { name: "UK Dividend Tax", href: "/uk-dividend-tax-calculator", desc: "Calculate tax on UK dividend income" },
            { name: "Stamp Duty Calculator (UK Shares)", href: "/uk-shares-stamp-duty-calculator", desc: "Calculate 0.5% SDRT on UK share purchases." },
            { name: "Share Dealing Fee Calculator", href: "/uk-share-dealing-fee-calculator", desc: "Analyze broker commissions, FX fees, and total trading costs." },
            { name: "Investment Growth Calculator", href: "/uk-investment-growth-calculator", desc: "Project future wealth using compound interest logic." },
            { name: "Dividend Yield Calculator", href: "/uk-dividend-yield-calculator", desc: "Calculate annual return % based on payouts and price." },
            { name: "Stocks & Shares ISA Calculator", href: "/uk-stocks-shares-isa-calculator", desc: "Track ISA allowance and project tax-free growth." },
            { name: "P/E Ratio Calculator", href: "/uk-pe-ratio-calculator", desc: "Calculate Price-to-Earnings ratio for UK stocks valuation." },
            { name: "Portfolio Return Calculator", href: "/portfolio-return-calculator-uk", desc: "Calculate weighted annual portfolio performance and CAGR." },
            { name: "Compound Interest Calculator", href: "/uk-compound-interest-calculator", desc: "Project long-term wealth growth with SIP and compounding frequency." },
            { name: "Risk & Volatility Calculator", href: "/risk-volatility-calculator-uk", desc: "Calculate Standard Deviation and Beta for UK stocks." },
            { name: "SIP Calculator", href: "/sip-calculator-uk", desc: "Calculate future value of monthly investments." },
            { name: "Inflation Adjusted Return", href: "/inflation-adjusted-return-calculator-uk", desc: "Calculate real returns after UK inflation." },
            { name: "FTSE Index Return", href: "/ftse-index-return-calculator-uk", desc: "Calculate historical CAGR for FTSE 100/250." },
        ],
    },
    {
        title: "Legal & Professional",
        icon: <Scale className="h-6 w-6 text-primary" />,
        calculators: [
            { name: "Inheritance Tax", href: "/inheritance-tax-calculator-uk", desc: "Estimate potential IHT payout" },
            { name: "Unfair Dismissal", href: "/unfair-dismissal-calculator-uk", desc: "Basic Award statutory estimator" },
            { name: "Personal Injury Comp", href: "/personal-injury-compensation-calculator-uk", desc: "Accident claim & JCG estimator" },
            { name: "Care Home Fees", href: "/care-home-fees-calculator-uk", desc: "Capital limits & funding means test" }
        ],
    },
    {
        title: "Astrology",
        icon: <Sparkles className="h-6 w-6 text-primary" />,
        calculators: [
            { name: "Sun Sign Calculator", href: "/sun-sign-calculator", desc: "Calculate your core zodiac identity" },
            { name: "Moon Sign Calculator", href: "/moon-sign-calculator", desc: "Discover your emotional inner self" },
            { name: "Rising Sign Calculator", href: "/rising-sign-calculator", desc: "Find your outward personality (Ascendant)" },
            { name: "Sun, Moon, Rising Calc", href: "/sun-moon-rising-calculator", desc: "Find your 'Big Three' astrology signs" },
            { name: "Venus Sign Calculator", href: "/venus-sign-calculator", desc: "Discover your love and attraction style" },
            { name: "Chiron Sign Calculator", href: "/chiron-sign-calculator", desc: "Understand your deepest wounds and healing" },
            { name: "Lilith Sign Calculator", href: "/lilith-sign-calculator", desc: "Explore your hidden raw energy" },
            { name: "North Node Calculator", href: "/north-node-calculator", desc: "Discover your soul's destiny and purpose" },
            { name: "Part of Fortune", href: "/part-of-fortune-calculator", desc: "Find where you encounter luck and joy" },
            { name: "Vertex Calculator", href: "/vertex-calculator", desc: "Understand fated encounters and destiny" },
        ],
    },
    {
        title: "Education & Grades",
        icon: <GraduationCap className="h-6 w-6 text-primary" />,
        calculators: [
            { name: "CGPA to Percentage", href: "/cgpa-to-percentage-calculator", desc: "Convert CGPA to percentage score" },
            { name: "SGPA to CGPA", href: "/sgpa-to-cgpa-calculator", desc: "Aggregate semester grades" },
            { name: "Marks Percentage", href: "/marks-percentage-calculator", desc: "Calculate exam marks percentage" },
            { name: "Percentage to CGPA", href: "/percentage-to-cgpa-calculator", desc: "Reverse grade conversion" },
            { name: "GPA Calculator", href: "/gpa-calculator", desc: "Calculate weighted GPA" },
            { name: "SGPA to Percentage", href: "/sgpa-to-percentage-calculator", desc: "Semester SGPA to %" },
            { name: "Final Grade", href: "/final-grade-calculator", desc: "Target grade estimator" },
        ],
    },
];

export const allCalculators = categories.flatMap(c => c.calculators);
