import { BreadcrumbSchema } from "@/components/seo/breadcrumb-schema";
import { AlertOctagon, Scale, ShieldAlert, Info, ExternalLink, Mail, Globe, AlertTriangle, FileText, Activity, Car, Home, Construction, Percent, TrendingUp, Dumbbell, Heart, Moon } from "lucide-react";

export const metadata = {
    title: "Disclaimer | CalZone - UK Calculator Hub",
    description: "Detailed disclaimer regarding the nature, limitations, and use of calculators and content on CalZone UK.",
};

export default function DisclaimerPage() {
    const breadcrumbs = [
        { name: "Home", item: "/" },
        { name: "Disclaimer", item: "/disclaimer" },
    ];

    const categories = [
        { icon: TrendingUp, label: "Finance" },
        { icon: Car, label: "Automotive" },
        { icon: Home, label: "Home & Property" },
        { icon: Construction, label: "Construction & DIY" },
        { icon: Percent, label: "Maths & Percentages" },
        { icon: TrendingUp, label: "Stock Market" },
        { icon: Dumbbell, label: "Fitness & Diet" },
        { icon: Heart, label: "General Health" },
        { icon: Moon, label: "Sleep & Recovery" },
    ];

    return (
        <div className="container mx-auto px-4 py-12 max-w-4xl">
            <BreadcrumbSchema items={breadcrumbs} />

            <header className="mb-12 border-b border-slate-200 dark:border-slate-800 pb-8">
                <div className="inline-flex items-center gap-2 px-3 py-1 bg-amber-500/10 text-amber-600 dark:text-amber-500 text-xs font-bold uppercase tracking-wider rounded-full mb-4">
                    <AlertOctagon className="w-4 h-4" /> Legal
                </div>
                <h1 className="text-3xl md:text-5xl font-extrabold text-slate-900 dark:text-slate-50">
                    Disclaimer
                </h1>
                <p className="text-slate-500 mt-4 font-medium italic">
                    Last Updated: March 2026 | Applies to all tools and content on thecalzone.co.uk
                </p>
                <p className="text-slate-600 dark:text-slate-400 mt-6 text-lg leading-relaxed">
                    CalZone is built to make everyday calculations faster, simpler and more accessible for people across the United Kingdom. Before you use our tools, please take a moment to read this Disclaimer. It sets out the nature and limitations of what we provide and helps you make the most informed use of our platform.
                </p>
            </header>

            <div className="prose prose-slate dark:prose-invert prose-lg max-w-none">

                <section className="mb-12">
                    <h2 className="flex items-center gap-3 text-2xl font-bold text-slate-900 dark:text-slate-50">
                        <ShieldAlert className="w-6 h-6 text-indigo-500" />
                        Using CalZone Means You Agree to These Terms
                    </h2>
                    <p>
                        By visiting and using any part of <strong>thecalzone.co.uk</strong>, including any of our calculators, written guides, blog articles or reference tools, you confirm that you have read, understood and accepted the terms set out in this Disclaimer. If you do not agree with these terms, we kindly ask that you refrain from using our platform. This Disclaimer applies equally to all categories of tools available on CalZone, including those covering health and fitness, personal finance, home, property, driving, investments, sleep and lifestyle.
                    </p>
                </section>

                <section className="mb-12 bg-slate-50 dark:bg-slate-900/50 p-8 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm transition-all duration-300 hover:shadow-md">
                    <h2 className="flex items-center gap-3 text-2xl font-bold text-slate-900 dark:text-slate-50 mt-0">
                        <Info className="w-6 h-6 text-blue-500" />
                        Our Tools Are for Guidance - Not Definitive Answers
                    </h2>
                    <div className="bg-white dark:bg-slate-800 p-4 rounded-xl border border-slate-100 dark:border-slate-700 mb-6 font-medium text-slate-700 dark:text-slate-300">
                        <span className="text-blue-600 dark:text-blue-400 font-bold uppercase text-xs block mb-1">Plain English</span>
                        CalZone gives you smart estimates to help you think through decisions. The results are not official figures and should not replace advice from a qualified professional.
                    </div>
                    <p>
                        Every calculator and tool published on CalZone has been designed to serve a single, clear purpose: to give UK residents fast, helpful estimates for everyday questions, from working out a calorie deficit and estimating road tax, to projecting investment growth or calculating stamp duty on shares.
                    </p>
                    <p>
                        All outputs generated by our tools are indicative estimates based on standardised assumptions and publicly available UK data sources. They are intended for general informational and educational purposes only. They do not constitute, and should not be treated as, definitive, legally binding or professionally certified figures of any kind.
                    </p>
                </section>

                <section className="mb-12">
                    <h2 className="flex items-center gap-3 text-2xl font-bold text-slate-900 dark:text-slate-50">
                        <Scale className="w-6 h-6 text-emerald-500" />
                        Accuracy, Data Sources & Inherent Limitations
                    </h2>
                    <p>
                        We take the accuracy of our calculators seriously. CalZone's tools are built with reference to trusted UK data sources, including published HMRC guidelines, NHS statistics, Bank of England rates, DVLA regulations and official government policy documentation.
                    </p>
                    <p>
                        However, there are inherent limitations to any online calculator that you should be aware of:
                    </p>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-6">
                        <div className="flex gap-4">
                            <div className="shrink-0 w-10 h-10 rounded-full bg-slate-100 dark:bg-slate-800 flex items-center justify-center font-bold text-slate-500">1</div>
                            <div>
                                <h4 className="font-bold text-slate-900 dark:text-slate-50 mb-1">Estimates, not guarantees</h4>
                                <p className="text-sm">Results are produced by mathematical models and standardised assumptions. Your individual circumstances may produce outcomes that differ from our estimates.</p>
                            </div>
                        </div>
                        <div className="flex gap-4">
                            <div className="shrink-0 w-10 h-10 rounded-full bg-slate-100 dark:bg-slate-800 flex items-center justify-center font-bold text-slate-500">2</div>
                            <div>
                                <h4 className="font-bold text-slate-900 dark:text-slate-50 mb-1">Regulatory changes</h4>
                                <p className="text-sm">UK legislation and policy guidelines change regularly. Although we work to keep our tools current, there may be a gap between a regulatory change and an update.</p>
                            </div>
                        </div>
                        <div className="flex gap-4">
                            <div className="shrink-0 w-10 h-10 rounded-full bg-slate-100 dark:bg-slate-800 flex items-center justify-center font-bold text-slate-500">3</div>
                            <div>
                                <h4 className="font-bold text-slate-900 dark:text-slate-50 mb-1">Technical limitations</h4>
                                <p className="text-sm">Our tools may occasionally be subject to calculation errors, display issues or unexpected behaviour resulting from technical anomalies.</p>
                            </div>
                        </div>
                        <div className="flex gap-4">
                            <div className="shrink-0 w-10 h-10 rounded-full bg-slate-100 dark:bg-slate-800 flex items-center justify-center font-bold text-slate-500">4</div>
                            <div>
                                <h4 className="font-bold text-slate-900 dark:text-slate-50 mb-1">Input dependency</h4>
                                <p className="text-sm">The quality of any result is directly tied to the accuracy of the information you enter. Incorrect inputs produce incorrect results.</p>
                            </div>
                        </div>
                    </div>
                </section>

                <section className="mb-12">
                    <h2 className="flex items-center gap-3 text-2xl font-bold text-slate-900 dark:text-slate-50">
                        <FileText className="w-6 h-6 text-purple-500" />
                        No Professional Relationship Is Created
                    </h2>
                    <p>
                        Using CalZone does not create any form of professional advisory relationship between you and CalZone or any individual associated with our platform. This applies without exception across all tool categories.
                    </p>
                    <p>Specifically, using our tools does not establish:</p>
                    <ul className="grid grid-cols-1 md:grid-cols-2 gap-2 list-none p-0">
                        <li className="flex items-center gap-2 bg-slate-50 dark:bg-slate-900 p-3 rounded-lg border border-slate-100 dark:border-slate-800">
                            <div className="w-1.5 h-1.5 rounded-full bg-purple-500" /> A financial adviser–client relationship
                        </li>
                        <li className="flex items-center gap-2 bg-slate-50 dark:bg-slate-900 p-3 rounded-lg border border-slate-100 dark:border-slate-800">
                            <div className="w-1.5 h-1.5 rounded-full bg-purple-500" /> A doctor–patient or clinical relationship
                        </li>
                        <li className="flex items-center gap-2 bg-slate-50 dark:bg-slate-900 p-3 rounded-lg border border-slate-100 dark:border-slate-800">
                            <div className="w-1.5 h-1.5 rounded-full bg-purple-500" /> A solicitor–client or legal advisory relationship
                        </li>
                        <li className="flex items-center gap-2 bg-slate-50 dark:bg-slate-900 p-3 rounded-lg border border-slate-100 dark:border-slate-800">
                            <div className="w-1.5 h-1.5 rounded-full bg-purple-500" /> An accountant–client or tax advisory relationship
                        </li>
                    </ul>
                    <p className="mt-6">
                        The results you receive are outputs of mathematical models, not personalised professional advice. Always consult a qualified, regulated professional before making any significant decision based on our results.
                    </p>
                </section>

                <section className="mb-12">
                    <h3 className="text-xl font-bold text-slate-900 dark:text-slate-50 mb-6">Category-Specific Guidance Notes</h3>
                    <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                        {categories.map((cat, idx) => (
                            <div key={idx} className="flex items-center gap-3 p-3 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl">
                                <cat.icon className="w-5 h-5 text-slate-400" />
                                <span className="text-sm font-medium text-slate-700 dark:text-slate-300">{cat.label}</span>
                            </div>
                        ))}
                    </div>
                </section>

                <section className="mb-12">
                    <h2 className="flex items-center gap-3 text-2xl font-bold text-slate-900 dark:text-slate-50">
                        < Globe className="w-6 h-6 text-cyan-500" />
                        UK Legislative and Market Changes
                    </h2>
                    <p>
                        The United Kingdom&apos;s tax, financial, and regulatory landscape evolves continuously. Annual Budget statements, HMRC threshold revisions, Bank of England base rate adjustments and changes to NHS guidelines can all affect the accuracy of our tools.
                    </p>
                    <p>
                        CalZone endeavours to update its calculators promptly following significant legislative changes. However, we cannot guarantee that every tool will reflect the most current figures at all times.
                    </p>
                    <div className="bg-amber-50 dark:bg-amber-950/30 p-6 rounded-2xl border border-amber-200 dark:border-amber-900/50 mt-8 relative overflow-hidden">
                        <div className="absolute top-0 right-0 p-4 opacity-10">
                            <AlertTriangle className="w-24 h-24 text-amber-500" />
                        </div>
                        <div className="flex items-start gap-4">
                            <div className="bg-amber-100 dark:bg-amber-900 p-2 rounded-lg">
                                <AlertTriangle className="w-6 h-6 text-amber-600 dark:text-amber-400" />
                            </div>
                            <div>
                                <h4 className="font-bold text-amber-900 dark:text-amber-100 mb-1 uppercase tracking-wider text-sm">Important</h4>
                                <p className="text-amber-800 dark:text-amber-200 m-0">
                                    If you are using CalZone around the time of a UK Budget, HMRC update or major policy announcement, we strongly recommend verifying key figures against official government sources such as <strong>gov.uk</strong> or <strong>hmrc.gov.uk</strong> before relying on our results.
                                </p>
                            </div>
                        </div>
                    </div>
                </section>

                <section className="mb-12">
                    <h2 className="flex items-center gap-3 text-2xl font-bold text-slate-900 dark:text-slate-50">
                        <ShieldAlert className="w-6 h-6 text-red-500" />
                        Limitation of Liability
                    </h2>
                    <p>
                        To the fullest extent permitted under the laws of England and Wales, CalZone and its operators accept no liability whatsoever for any loss, damage, cost or consequence, whether direct, indirect, financial, physical or otherwise, arising from your use of or reliance upon, any calculator, tool, article or other content published on thecalzone.co.uk.
                    </p>
                    <p>
                        This includes, but is not limited to, financial losses, health consequences and any loss arising from inaccuracies, outdated data or technical errors within our calculators. All use of CalZone&apos;s tools is entirely at your own risk.
                    </p>
                </section>

                <section className="mb-12">
                    <h2 className="flex items-center gap-3 text-2xl font-bold text-slate-900 dark:text-slate-50">
                        <ExternalLink className="w-6 h-6 text-blue-500" />
                        External Links and Third-Party Resources
                    </h2>
                    <p>
                        CalZone may include links to external websites, such as official government portals, NHS pages or HMRC guidance. These links are provided purely for your convenience. We do not control the content or availability of any external website, and the inclusion of a link does not constitute an endorsement.
                    </p>
                </section>

                <section className="mb-12">
                    <h2 className="flex items-center gap-3 text-2xl font-bold text-slate-900 dark:text-slate-50">
                        <Activity className="w-6 h-6 text-emerald-500" />
                        Platform Availability and &quot;As Is&quot; Use
                    </h2>
                    <p>
                        CalZone is provided on an &quot;as is&quot; and &quot;as available&quot; basis. We do not warrant that the website will be available at all times, free from interruption, or that all calculator outputs will be error-free or completely accurate.
                    </p>
                </section>

                <section className="mb-12 p-8 bg-slate-900 dark:bg-slate-800 rounded-3xl text-white">
                    <div className="md:flex items-center justify-between gap-8">
                        <div className="mb-6 md:mb-0">
                            <h2 className="text-2xl font-bold mb-4 text-white mt-0 italic">Reporting an Inaccuracy</h2>
                            <p className="text-slate-300 m-0">
                                We genuinely value accuracy and take any reported errors seriously. If you believe one of our calculators is producing incorrect results, please let us know. Your feedback helps us improve CalZone for everyone.
                            </p>
                        </div>
                        <div className="space-y-4 shrink-0">
                            <a href="mailto:info@thecalzone.co.uk" className="flex items-center gap-3 bg-white/10 hover:bg-white/20 transition-colors p-4 rounded-2xl border border-white/10">
                                <Mail className="w-5 h-5 text-blue-400" />
                                <span className="font-medium">info@thecalzone.co.uk</span>
                            </a>
                            <div className="flex items-center gap-3 bg-white/10 p-4 rounded-2xl border border-white/10 opacity-70">
                                <Globe className="w-5 h-5 text-emerald-400" />
                                <span className="font-medium">thecalzone.co.uk</span>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    );
}
