import { BreadcrumbSchema } from "@/components/seo/breadcrumb-schema";
import { AlertOctagon, Scale, ShieldAlert } from "lucide-react";

export const metadata = {
    title: "Medical & Financial Disclaimer | CalZone UK",
    description: "Important legal and medical disclaimers regarding the algorithmic tools provided by CalZone.",
};

export default function DisclaimerPage() {
    const breadcrumbs = [
        { name: "Home", item: "/" },
        { name: "Disclaimer", item: "/disclaimer" },
    ];

    return (
        <div className="container mx-auto px-4 py-12 max-w-4xl">
            <BreadcrumbSchema items={breadcrumbs} />

            <header className="mb-12 border-b border-slate-200 dark:border-slate-800 pb-8">
                <div className="inline-flex items-center gap-2 px-3 py-1 bg-amber-500/10 text-amber-600 dark:text-amber-500 text-xs font-bold uppercase tracking-wider rounded-full mb-4">
                    <AlertOctagon className="w-4 h-4" /> Legal
                </div>
                <h1 className="text-3xl md:text-5xl font-extrabold text-slate-900 dark:text-slate-50">
                    Medical & Financial Disclaimer
                </h1>
                <p className="text-slate-500 mt-4 font-medium">Last updated: March 2026</p>
            </header>

            <div className="prose prose-slate dark:prose-invert prose-lg max-w-none">
                <div className="bg-slate-50 dark:bg-slate-900/50 p-6 rounded-2xl border border-slate-200 dark:border-slate-800 mb-10 text-slate-700 dark:text-slate-300">
                    <p className="m-0 font-medium">
                        The calculators, algorithms, and content provided on <strong>CalZone (thecalzone.co.uk)</strong> are designed for general educational and informational purposes only. By using this website, you agree to the following terms.
                    </p>
                </div>

                <h2 className="flex items-center gap-3">
                    <ShieldAlert className="w-6 h-6 text-indigo-500" />
                    Medical Disclaimer
                </h2>
                <p>
                    CalZone provides computational tools such as the BMI Calculator, Calorie Deficit Calculator, and Water Intake Calculator, utilizing widely accepted mathematical formulas (such as the Mifflin-St Jeor equation).
                </p>
                <ul>
                    <li><strong>Not a Substitute for Professional Advice:</strong> The information generated by our tools is not intended to be a substitute for professional medical advice, diagnosis, or treatment.</li>
                    <li><strong>Consult Your GP:</strong> Always seek the advice of your physician, dietician, or other qualified health provider with any questions you may have regarding a medical condition or dietary changes.</li>
                    <li><strong>Estimations Only:</strong> Human biology is highly complex. Our algorithms provide estimates based on generalized averages. They cannot account for individual metabolic variations, hormonal imbalances, existing illnesses, or specific physiological needs (such as pregnancy, unless explicitly stated).</li>
                    <li><strong>Emergency:</strong> If you think you may have a medical emergency, call your doctor or 999 immediately. Do not rely on electronic communications or tools on this website for immediate, urgent medical needs.</li>
                </ul>

                <h2 className="flex items-center gap-3">
                    <Scale className="w-6 h-6 text-emerald-500" />
                    Financial & Tax Disclaimer
                </h2>
                <p>
                    CalZone provides financial estimation tools, including Holiday Budgeting, Road Tax calculations, and Property estimators, intended to assist users with personal planning.
                </p>
                <ul>
                    <li><strong>No Financial Advice:</strong> We are not independent financial advisors, accountants, or tax professionals. The results presented by our calculators do not constitute financial advice.</li>
                    <li><strong>Data Fluctuations:</strong> While we strive to base our calculators on current UK rates (e.g., HMRC brackets), tax laws, financial regulations, and market prices are subject to frequent change. Your actual costs or liabilities may differ.</li>
                    <li><strong>Independent Verification Required:</strong> You must not rely on the information on this website as an alternative to financial advice from an appropriately qualified professional. Ensure you independently verify all figures before making any major financial commitment or submitting tax filings.</li>
                </ul>

                <h2>No Warranties</h2>
                <p>
                    While we make every effort to ensure the mathematical accuracy of our codebase, the information and tools on this website are provided "as is" without any representations or warranties, express or implied. CalZone makes no representations or warranties in relation to the completeness, accuracy, reliability, or availability of the website or the information, products, services, or related graphics contained on the website for any purpose.
                </p>

                <h2>Limitation of Liability</h2>
                <p>
                    In no event will CalZone, its owners, developers, or affiliates be liable for any loss or damage including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of this website and its calculators.
                </p>
            </div>
        </div>
    );
}
